# 异步函数

## async

在es8之前,如果想使用异步函数,就需要在期约的执行器中去定义,这样做每次都要声明一个期约,造成不必要的麻烦,在es8之后推出了async/await关键字,可以让普通函数具有异步特性. 可以理解为使用async的函数等价于执行器函数,而且最终会按照resolve的方法返回



箭头函数,普通函数声明,表达式函数都可以使用async

```JavaScript
async function foo(){}
let bar = async function(){}
let baz = async ()=>{}
```



使用async的函数与普通函数没有太大区别,唯一区别是返回值会返回一个用resolve包装的期约

```JavaScript
async function foo(){
  return 1
}

let p=foo()
p.then(()=>setTimeout(console.log,0,p))
```

![image-20220930162513331](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220930162513331.png)

当然直接返回期约也是可以的

```JavaScript
async function bar(){
  console.log(1)
  return Promise.resolve(3)
}

bar().then((value)=>setTimeout(console.log,0,value))
console.log(2);
```

![image-20220930162551269](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220930162551269.png)



async的返回值期待一个实现了thenable的接口,如果实现了接口,就可以使用then中的函数对对象解包

```JavaScript
async function foo() {
  let bar = {
    then(callback) {
      callback([3, 4, 5]);
    },
  };
  return bar;
}
let p = foo();
p.then((x) => {
  let arr = [1, 2];
  arr = arr.concat(x);
  console.log(arr);
});
```

![image-20220930162625338](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220930162625338.png)



如果在异步函数中抛出错误或者返回一个拒绝的期约,那么也会让返回值成为一个拒绝的期约(也就是在异步函数内生成的错误会被捕获),但是如果声明一个拒绝的期约但是没有用return返回，异步函数是不会捕获的

```JavaScript
async function foo(){
  throw Error("foo")
}

// foo()
foo().catch((reason)=>{setTimeout(console.log,0,reason)})

async function bar(){
  return Promise.reject("bar")
}

bar().catch((reason)=>{console.log(reason)})

async function baz(){
  console.log(1);
  Promise.reject(3); //不会捕获拒绝期约产生的错误(前面加上await就可以被捕获了)
  console.log(2);//出现错误也不会停止下面函数的执行
}

console.log(baz());//依旧生成一个期约,但这个期约是解决状态
```

![image-20220930162704233](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220930162704233.png)



## await

在异步函数中,经常要处理并非立即完成的任务(例如下载安装包),所以就有暂停功能的必要，await可以暂停后面的代码，会尝试对await后面的代码进行解包并拿到其值。

//await可以单独使用，也可以和表达式一起使用

```JavaScript
function foo(){
  await Promise.resolve("8")//无效代码,因为await必须与异步函数一起使用
}
```

![image-20221001081951588](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20221001081951588.png)

await等待一个期约时,会返回这个期约resolve值

```JavaScript
async function foo() {
  console.log(await Promise.resolve("8"));
  // console.log(await Promise.reject("9"));
}
foo();

async function bar() {
  console.log(await "bar");
}
bar();
```

![image-20221001082027321](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20221001082027321.png)

await 会期待一个实现then接口的对象,如果await等待的是这类对象,就会尝试解包并获取其值

```javascript
async function baz() {
  let o = {
    then(callback) {
      callback("baz");//不太清楚这个then接口到底是怎么在没有传入callback的时候调用并让await解包的
    },
  };
  console.log(await o);
}
baz();
```

![image-20221001082104617](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20221001082104617.png)

如果await等待的函数内部出错,就会抛出错误

```JavaScript
async function foo(){
  await (function(){throw 9})();
}
foo()// 如果正常抛出错误,异步函数可以捕获,但如果前面跟着await,那么就不会被捕获
```

![image-20221001082135153](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20221001082135153.png)

```JavaScript
async function bar(){
  console.log(1);
  await Promise.reject(3);
  console.log(4);//注意这行代码不会执行,与async不同
}
bar().catch(console.log)
console.log(2);
```

![image-20221001082158298](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20221001082158298.png)

